export const propertyTypeConfig = {
  "Rooms": {
    // bedrooms: { label: "Bedrooms", type: "select", options: ["0", "1", "2", "3", "4", "5", "<5"], name: "bedrooms" },
    // bathrooms: { label: "Bathrooms", type: "select", options: ["0", "1", "2", "3", "4", "5", "<5"], name: "bathrooms" },
    // kitchen: { label: "Kitchen", type: "select", options: ["No", "Yes"], name: "kitchen" },
    livingArea: { label: "Living Area", type: "select", options: ["No", "Yes"], name: "livingArea" },
    internet: { label: "Internet", type: "select", options: ["No", "Yes"], name: "internet" },
    parking: { label: "Parking", type: "select", options: ["No", "Yes"], name: "parking" },
    roomService: { label: "Room Service", type: "select", options: ["No", "Yes"], name: "roomService" },
    receptionService: { label: "Reception Service", type: "select", options: ["No", "Yes"], name: "receptionService" },
    swimmingPool: { label: "Swimming Pool", type: "select", options: ["No", "Yes"], name: "swimmingPool" },
    checkInTime:{label: "Check In Time", type: "select",options: ["24 Hours","00:00","01:00","02:00","03:00","04:00","05:00","06:00","07:00","08:00","09:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00","21:00","22:00","23:00","24 Hours"], name: "checkInTime"},
    checkOutTime:{label: "Check Out Time", type: "select",options: ["24 Hours","00:00","01:00","02:00","03:00","04:00","05:00","06:00","07:00","08:00","09:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00","21:00","22:00","23:00","24 Hours"], name: "checkOutTime"},
  },
  "Halls": {
    buildupAreaUnit: { label: " buildupAreaUnit", type: "select", options: ["Sq.yd", "Sq.ft", "Sq.mtr"], name: "buildupAreaUnit" },
    propertyArea: { label: "Property Area", type: "number", placeholder: "Property Area", name: "propertyArea" },
    buildupArea: { label: "Build up Area", type: "number", placeholder: "Build up Area", name: "buildupArea" },
    parking: { label: "Parking", type: "select", options: ["No", "Yes"], name: "parking" },
    capacity: { label: "Capacity", type: "select", options: ["<50", "100", "200", "300", "500", "<500", "<1000"], name: "capacity" },
    checkInTime:{label: "Check In Time", type: "select",options: ["24 Hours","00:00","01:00","02:00","03:00","04:00","05:00","06:00","07:00","08:00","09:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00","21:00","22:00","23:00","24 Hours"], name: "Check In Time"},
    checkOutTime:{label: "Check Out Time", type: "select",options: ["24 Hours","00:00","01:00","02:00","03:00","04:00","05:00","06:00","07:00","08:00","09:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00","21:00","22:00","23:00","24 Hours"], name: "Check Out Time"},
  },
  "Commercial": {
    buildupAreaUnit: { label: " buildupAreaUnit", type: "select", options: ["Sq.yd", "Sq.ft", "Sq.mtr"], name: "buildupAreaUnit" },
    propertyArea: { label: "Property Area", type: "number", placeholder: "Property Area", name: "propertyArea" },
    buildupArea: { label: "Build up Area", type: "number", placeholder: "Build up Area", name: "buildupArea" },
    plinthArea: { label: "Plinth Area", type: "number", placeholder: "Plinth Area", name: "plinthArea" },
    floor: { label: "Floor", type: "number", placeholder: "Floor", name: "floor" },
    facing: { label: "Facing", type: "select", options: ["East", "West", "North", "South"], name: "facing" },
    balcony: { label: "Balcony", type: "select", options: ["No", "Yes"], name: "balcony" },
    lift: { label: "Lift", type: "select", options: ["No", "Yes"], name: "lift" },
    parking: { label: "Parking", type: "select", options: ["No", "Yes"], name: "parking" },
    monthlyMaintenance: { label: "Monthly Maintenance", type: "number", name: "monthlyMaintenance" },
    ageOfProperty: { label: "Age of Property", type: "number", name: "ageOfProperty" },
    projectName: { label: "Building/Project Name", type: "text", name: "projectName" },
    uds: { label: "UDS", type: "text", name: "uds" },
  },
  "House": {
    buildupAreaUnit: { label: " buildupAreaUnit", type: "select", options: ["Sq.yd", "Sq.ft", "Sq.mtr"], name: "buildupAreaUnit" },
    propertyArea: { label: "Property Area", type: "number", placeholder: "Property Area", name: "propertyArea" },
    buildupArea: { label: "Build up Area", type: "number", placeholder: "Build up Area", name: "buildupArea" },
    plinthArea: { label: "Plinth Area", type: "number", placeholder: "Plinth Area", name: "plinthArea" },
    floor: { label: "Floor", type: "number", placeholder: "Floor", name: "floor" },
    facing: { label: "Facing", type: "select", options: ["East", "West", "North", "South"], name: "facing" },
    balcony: { label: "Balcony", type: "select", options: ["No", "Yes"], name: "balcony" },
    lift: { label: "Lift", type: "select", options: ["No", "Yes"], name: "lift" },
    parking: { label: "Parking", type: "select", options: ["No", "Yes"], name: "parking" },
    monthlyMaintenance: { label: "Monthly Maintenance", type: "number", name: "monthlyMaintenance" },
    ageOfProperty: { label: "Age of Property", type: "number", name: "ageOfProperty" },
    projectName: { label: "Building/Project Name", type: "text", name: "projectName" },
    uds: { label: "UDS", type: "text", name: "uds" },
  },
  "Villa": {
    buildupAreaUnit: { label: " buildupAreaUnit", type: "select", options: ["Sq.yd", "Sq.ft", "Sq.mtr"], name: "buildupAreaUnit" },
    propertyArea: { label: "Property Area", type: "number", placeholder: "Property Area", name: "propertyArea" },
    buildupArea: { label: "Build up Area", type: "number", placeholder: "Build up Area", name: "buildupArea" },
    plinthArea: { label: "Plinth Area", type: "number", placeholder: "Plinth Area", name: "plinthArea" },
    floor: { label: "Floor", type: "number", placeholder: "Floor", name: "floor" },
    facing: { label: "Facing", type: "select", options: ["East", "West", "North", "South"], name: "facing" },
    balcony: { label: "Balcony", type: "select", options: ["No", "Yes"], name: "balcony" },
    lift: { label: "Lift", type: "select", options: ["No", "Yes"], name: "lift" },
    parking: { label: "Parking", type: "select", options: ["No", "Yes"], name: "parking" },
    monthlyMaintenance: { label: "Monthly Maintenance", type: "number", name: "monthlyMaintenance" },
    ageOfProperty: { label: "Age of Property", type: "number", name: "ageOfProperty" },
    projectName: { label: "Building/Project Name", type: "text", name: "projectName" },
    uds: { label: "UDS", type: "text", name: "uds" },
  },
  "Hotels": {
    // bedrooms: { label: "Bedrooms", type: "select", options: ["0", "1", "2", "3", "4", "5", "<5"], name: "bedrooms" },
    // bathrooms: { label: "Bathrooms", type: "select", options: ["0", "1", "2", "3", "4", "5", "<5"], name: "bathrooms" },
    // kitchen: { label: "Kitchen", type: "select", options: ["No", "Yes"], name: "kitchen" },
    livingArea: { label: "Living Area", type: "select", options: ["No", "Yes"], name: "livingArea" },
    internet: { label: "Internet", type: "select", options: ["No", "Yes"], name: "internet" },
    parking: { label: "Parking", type: "select", options: ["No", "Yes"], name: "parking" },
    roomService: { label: "Room Service", type: "select", options: ["No", "Yes"], name: "roomService" },
    receptionService: { label: "Reception Service", type: "select", options: ["No", "Yes"], name: "receptionService" },
    cleaningService:{label: "Cleaning Service", type: "select", options: ["No", "Yes"], name: "cleaningService" },
    barFacility:{label: "Bar Facility", type: "select", options: ["No", "Yes"], name: "barFacility"},
    swimmingPool: { label: "Swimming Pool", type: "select", options: ["No", "Yes"], name: "swimmingPool" },
    checkInTime:{label: "Check In Time", type: "select",options: ["24 Hours","00:00","01:00","02:00","03:00","04:00","05:00","06:00","07:00","08:00","09:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00","21:00","22:00","23:00","24 Hours"], name: "Check In Time"},
    checkOutTime:{label: "Check Out Time", type: "select",options: ["24 Hours","00:00","01:00","02:00","03:00","04:00","05:00","06:00","07:00","08:00","09:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00","21:00","22:00","23:00","24 Hours"], name: "Check Out Time"},
  },
"Resorts": {
    // bedrooms: { label: "Bedrooms", type: "select", options: ["0", "1", "2", "3", "4", "5", "<5"], name: "bedrooms" },
    // bathrooms: { label: "Bathrooms", type: "select", options: ["0", "1", "2", "3", "4", "5", "<5"], name: "bathrooms" },
    // kitchen: { label: "Kitchen", type: "select", options: ["No", "Yes"], name: "kitchen" },
    livingArea: { label: "Living Area", type: "select", options: ["No", "Yes"], name: "livingArea" },
    internet: { label: "Internet", type: "select", options: ["No", "Yes"], name: "internet" },
    parking: { label: "Parking", type: "select", options: ["No", "Yes"], name: "parking" },
    roomService: { label: "Room Service", type: "select", options: ["No", "Yes"], name: "roomService" },
    receptionService: { label: "Reception Service", type: "select", options: ["No", "Yes"], name: "receptionService" },
    cleaningService:{label: "Cleaning Service", type: "select", options: ["No", "Yes"], name: "cleaningService" },
    barFacility:{label: "Bar Facility", type: "select", options: ["No", "Yes"], name: "barFacility"},
    swimmingPool: { label: "Swimming Pool", type: "select", options: ["No", "Yes"], name: "swimmingPool" },
    checkInTime:{label: "Check In Time", type: "select",options: ["24 Hours","00:00","01:00","02:00","03:00","04:00","05:00","06:00","07:00","08:00","09:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00","21:00","22:00","23:00","24 Hours"], name: "Check In Time"},
    checkOutTime:{label: "Check Out Time", type: "select",options: ["24 Hours","00:00","01:00","02:00","03:00","04:00","05:00","06:00","07:00","08:00","09:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00","21:00","22:00","23:00","24 Hours"], name: "Check Out Time"},
  },
"Farmhouses": {
    // bedrooms: { label: "Bedrooms", type: "select", options: ["0", "1", "2", "3", "4", "5", "<5"], name: "bedrooms" },
    // bathrooms: { label: "Bathrooms", type: "select", options: ["0", "1", "2", "3", "4", "5", "<5"], name: "bathrooms" },
    // kitchen: { label: "Kitchen", type: "select", options: ["No", "Yes"], name: "kitchen" },
    livingArea: { label: "Living Area", type: "select", options: ["No", "Yes"], name: "livingArea" },
    internet: { label: "Internet", type: "select", options: ["No", "Yes"], name: "internet" },
    parking: { label: "Parking", type: "select", options: ["No", "Yes"], name: "parking" },
    roomService: { label: "Room Service", type: "select", options: ["No", "Yes"], name: "roomService" },
    receptionService: { label: "Reception Service", type: "select", options: ["No", "Yes"], name: "receptionService" },
    cleaningService:{label: "Cleaning Service", type: "select", options: ["No", "Yes"], name: "cleaningService" },
    barFacility:{label: "Bar Facility", type: "select", options: ["No", "Yes"], name: "barFacility"},
    swimmingPool: { label: "Swimming Pool", type: "select", options: ["No", "Yes"], name: "swimmingPool" },
    checkInTime:{label: "Check In Time", type: "select",options: ["24 Hours","00:00","01:00","02:00","03:00","04:00","05:00","06:00","07:00","08:00","09:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00","21:00","22:00","23:00","24 Hours"], name: "Check In Time"},
    checkOutTime:{label: "Check Out Time", type: "select",options: ["24 Hours","00:00","01:00","02:00","03:00","04:00","05:00","06:00","07:00","08:00","09:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00","21:00","22:00","23:00","24 Hours"], name: "Check Out Time"},
  },
  "Guesthouses": {
    // bedrooms: { label: "Bedrooms", type: "select", options: ["0", "1", "2", "3", "4", "5", "<5"], name: "bedrooms" },
    // bathrooms: { label: "Bathrooms", type: "select", options: ["0", "1", "2", "3", "4", "5", "<5"], name: "bathrooms" },
    // kitchen: { label: "Kitchen", type: "select", options: ["No", "Yes"], name: "kitchen" },
    livingArea: { label: "Living Area", type: "select", options: ["No", "Yes"], name: "livingArea" },
    internet: { label: "Internet", type: "select", options: ["No", "Yes"], name: "internet" },
    parking: { label: "Parking", type: "select", options: ["No", "Yes"], name: "parking" },
    roomService: { label: "Room Service", type: "select", options: ["No", "Yes"], name: "roomService" },
    receptionService: { label: "Reception Service", type: "select", options: ["No", "Yes"], name: "receptionService" },
    cleaningService:{label: "Cleaning Service", type: "select", options: ["No", "Yes"], name: "cleaningService" },
    barFacility:{label: "Bar Facility", type: "select", options: ["No", "Yes"], name: "barFacility"},
    swimmingPool: { label: "Swimming Pool", type: "select", options: ["No", "Yes"], name: "swimmingPool" },
    checkInTime:{label: "Check In Time", type: "select",options: ["24 Hours","00:00","01:00","02:00","03:00","04:00","05:00","06:00","07:00","08:00","09:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00","21:00","22:00","23:00","24 Hours"], name: "Check In Time"},
    checkOutTime:{label: "Check Out Time", type: "select",options: ["24 Hours","00:00","01:00","02:00","03:00","04:00","05:00","06:00","07:00","08:00","09:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00","21:00","22:00","23:00","24 Hours"], name: "Check Out Time"},
  },
"Swimmingpools": {
  propertyArea: { label: "Property Area", type: "number", placeholder: "Property Area", name: "propertyArea" },
  buildupAreaUnit: { label: " buildupAreaUnit", type: "select", options: ["Sq.yd", "Sq.ft", "Sq.mtr"], name: "buildupAreaUnit" },
  parking: { label: "Parking", type: "select", options: ["No", "Yes"], name: "parking" },
    
  changingRoom:{label: "Changing Room", type: "select", options: ["No", "Yes"], name: "changingRoom"},
  washRoom:{label: "Wash Room", type: "select", options: ["No", "Yes"], name: "washRoom"},
  restaurants:{label: "Restaurants", type: "select", options: ["No", "Yes"], name: "restaurants"},
  internet:{label: "Internet", type: "select", options: ["No", "Yes"], name: "internet"},
  poolUtility:{label: "Pool Utility", type: "select", options: ["No", "Yes"], name: "poolUtility"},
  poolDesign:{label: "Pool Design", type: "select", options: ["No", "Yes"], name: "poolDesign"},
  Spa:{label: "Spa", type: "select", options: ["No", "Yes"], name: "spa"},
  checkInTime:{label: "Check In Time", type: "select",options: ["24 Hours","00:00","01:00","02:00","03:00","04:00","05:00","06:00","07:00","08:00","09:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00","21:00","22:00","23:00","24 Hours"], name: "Check In Time"},
    checkOutTime:{label: "Check Out Time", type: "select",options: ["24 Hours","00:00","01:00","02:00","03:00","04:00","05:00","06:00","07:00","08:00","09:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00","21:00","22:00","23:00","24 Hours"], name: "Check Out Time"},
  },

  "Hostels":{
    gender:{label: "Gender", type: "select", options: ["Male", "Female", "others"], name: "gender"},
    sharing:{label: "Sharing", type: "select", options: ["single", "double", "triple", "custom"], name: "Sharing"},
    foodchoice:{label: "Food Choice", type: "select", options: ["Veg", "Non-veg", "Veg/Non-veg"], name: "foodchoice"},
    internet:{label: "Internet", type: "select", options: ["No", "Yes"], name: "internet"},
    security:{label: "Security", type: "select", options: ["No", "Yes"], name: "security"},
    lockerfecility:{label: "Locker Fecility", type: "select", options: ["No", "Yes"], name: "lockerfecility"},
    library:{label: "Library", type: "select", options: ["No", "Yes"], name: "library"},
    readingRoom:{label: "Reading Room", type: "select", options: ["No", "Yes"], name: "readingRoom"},
    checkInTime:{label: "Check In Time", type: "select",options: ["24 Hours","00:00","01:00","02:00","03:00","04:00","05:00","06:00","07:00","08:00","09:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00","21:00","22:00","23:00","24 Hours"], name: "Check In Time"},
    checkOutTime:{label: "Check Out Time", type: "select",options: ["24 Hours","00:00","01:00","02:00","03:00","04:00","05:00","06:00","07:00","08:00","09:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00","21:00","22:00","23:00","24 Hours"], name: "Check Out Time"},
  },
  "Flats": {
    propertyArea: { label: "Property Area", type: "number", placeholder: "Property Area", name: "propertyArea" },
    buildupArea: { label: "Build up Area", type: "number", placeholder: "Build up Area", name: "buildupArea" },
    plinthArea: { label: "Plinth Area", type: "number", placeholder: "Plinth Area", name: "plinthArea" },
    floor: { label: "Floor", type: "number", placeholder: "Floor", name: "floor" },
    // buildupAreaUnit: { label: " buildupAreaUnit", type: "select", options: ["Sq.yd", "Sq.ft", "Sq.mtr"], name: "buildupAreaUnit" },
    facing: { label: "Facing", type: "select", options: ["East", "West", "North", "South"], name: "facing" },
    balcony: { label: "Balcony", type: "select", options: ["No", "Yes"], name: "balcony" },
    lift: { label: "Lift", type: "select", options: ["No", "Yes"], name: "lift" },
    parking: { label: "Parking", type: "select", options: ["No", "Yes"], name: "parking" },
    monthlyMaintenance: { label: "Monthly Maintenance", type: "number", name: "monthlyMaintenance" },
    ageOfProperty: { label: "Age of Property", type: "number", name: "ageOfProperty" },
    projectName: { label: "Building/Project Name", type: "text", name: "projectName" },
    // uds: { label: "UDS", type: "text", name: "uds" },
    bedrooms: { label: "Bedrooms", type: "select", options: ["0", "1", "2", "3", "4", "5", "<5"], name: "bedrooms" },
    bathrooms: { label: "Bathrooms", type: "select", options: ["0", "1", "2", "3", "4", "5", "<5"], name: "bathrooms" },
    furnished:{label: "Furnished", type: "select", options: ["unfurnished", "semi furnished", "furnished"], name: "Furnished"},
  },
  "Plots": {
    propertyArea: { label: "Property Area", type: "number", placeholder: "Property Area", name: "propertyArea" },
    buildupArea: { label: "Build up Area", type: "number", placeholder: "Build up Area", name: "buildupArea" },
    plinthArea: { label: "Plinth Area", type: "number", placeholder: "Plinth Area", name: "plinthArea" },
    floor: { label: "Floor", type: "number", placeholder: "Floor", name: "floor" },
    // buildupAreaUnit: { label: " buildupAreaUnit", type: "select", options: ["Sq.yd", "Sq.ft", "Sq.mtr"], name: "buildupAreaUnit" },
    facing: { label: "Facing", type: "select", options: ["East", "West", "North", "South"], name: "facing" },
    balcony: { label: "Balcony", type: "select", options: ["No", "Yes"], name: "balcony" },
    lift: { label: "Lift", type: "select", options: ["No", "Yes"], name: "lift" },
    parking: { label: "Parking", type: "select", options: ["No", "Yes"], name: "parking" },
    monthlyMaintenance: { label: "Monthly Maintenance", type: "number", name: "monthlyMaintenance" },
    ageOfProperty: { label: "Age of Property", type: "number", name: "ageOfProperty" },
    projectName: { label: "Building/Project Name", type: "text", name: "projectName" },
    // uds: { label: "UDS", type: "text", name: "uds" },
    bedrooms: { label: "Bedrooms", type: "select", options: ["0", "1", "2", "3", "4", "5", "<5"], name: "bedrooms" },
    bathrooms: { label: "Bathrooms", type: "select", options: ["0", "1", "2", "3", "4", "5", "<5"], name: "bathrooms" },
    furnished:{label: "Furnished", type: "select", options: ["unfurnished", "semi furnished", "furnished"], name: "Furnished"},
  },
  "Farmlands": {
    buildupAreaUnit: { label: " buildupAreaUnit", type: "select", options: ["Sq.yd", "Sq.ft", "Sq.mtr"], name: "buildupAreaUnit" },
    propertyArea: { label: "Property Area", type: "number", placeholder: "Property Area", name: "propertyArea" },
    buildupArea: { label: "Build up Area", type: "number", placeholder: "Build up Area", name: "buildupArea" },
    plinthArea: { label: "Plinth Area", type: "number", placeholder: "Plinth Area", name: "plinthArea" },
    crops:{label: "Crops", type: "text", placeholder: "Crops", name: "crops"},
    passageType:{label: "Passage Type", type: "select", options: ["Common", "Seperate"], name: "passageType"},
    waterSource:{label: "Water Source", type: "select", options: ["self", "canal", "rain", "river", "tank", "pond"], name: "waterSource"},
    
  },
};


export const propertyTypeArray = [
  "Rooms",
  "Halls",
  "Commercial",
  "House",
  "Villa",
  "Hotels",
  "Resorts",
  "Farmhouses",
  "Guesthouses",
  "Swimmingpools",
  "Hostels",
  "Flats",
  "Plots",
  "Farmlands",
];